# Generated by Django 5.0 on 2024-04-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_studentdetail_delete_studentdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetail',
            old_name='conformpassword',
            new_name='confirmpassword',
        ),
    ]
