# Generated by Django 5.0 on 2024-04-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('conformpassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
