# Generated by Django 5.0 on 2024-04-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_studentdetail_confirmpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentDetail',
        ),
    ]
